[package]
name = "ics06-solomachine"
version = "0.1.0"
edition = "2021"
keywords     = ["solomachine", "ics06", "cosmos", "ibc"]
repository   = "https://github.com/octopus-network/ics06-solomachine.git"
authors      = ["Octopus Network"]
description  = """
    Implementation of the ICS06 solomachine client according by ibc-go.
"""

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ibc = { version = "0.41.0", features = ["serde", "parity-scale-codec", "borsh"], default-features = false }
ibc-proto = { version = "0.30.0", features = ["parity-scale-codec", "borsh"], default-features = false }
prost = { version = "0.11", default-features = false }
displaydoc = { version = "0.2", default-features = false }
bytes = { version = "1.2.1", default-features = false }
eyre = { version = "0.6", default-features = false }
serde_derive = { version = "1.0.104", default-features = false }
serde = { version = "1.0", default-features = false}
serde_json = { version = "1", default-features = false }
erased-serde = { version = "0.3", default-features = false, features = ["alloc"] }
k256 = { version = "0.13", features = ["ecdsa", "sha256"], default-features = false }
tendermint = { version = "0.31", features = ["secp256k1", "rust-crypto"], default-features = false }
rand_core = { version = "0.6", default-features = false }
subtle-encoding = { version = "0.5", default-features = false }

## for codec encode or decode
parity-scale-codec = { version = "3.0.0", default-features = false, features = ["full"], optional = true }
scale-info = { version = "2.1.2", default-features = false, features = ["derive"], optional = true }
## for borsh encode or decode
borsh = {version = "0.10.0", default-features = false, optional = true }

# for publicKey
ed25519-dalek = { version = "1.0.1", features = ["serde", "u64_backend"], default-features = false }
secp256k1 = { version = "0.27.0", features = ["serde", "rand", "recovery", "alloc"], default-features = false }

[dev-dependencies]
hex-literal = "0.4"

[features]
default = ["std"]
std = [
    "ibc/std",
    "ibc-proto/std",
    "prost/std",
    "displaydoc/std",
    "bytes/std",
    "serde/std",
    "serde_json/std",
    "erased-serde/std",
    "k256/std",
    "tendermint/std",
    "rand_core/std",
    "subtle-encoding/std",
    "ed25519-dalek/std",
    "secp256k1/std",
]

parity-scale-codec = ["dep:parity-scale-codec", "dep:scale-info"]
borsh = ["dep:borsh"]

[patch.crates-io]
ibc-proto = { git = "https://github.com/DaviRain-Su/ibc-proto-rs.git", branch = "full-cosmos-type-v0.30.0" }
