[package]
name = "ics06-solomachine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ibc = { version = "0.40.0", git = "https://github.com/cosmos/ibc-rs.git", branch = "main", default-feature = false }
ibc-proto = { version = "0.29.0", git = "https://github.com/octopus-network/ibc-proto-rs.git", branch = "new-proto-v0.29.0", default-feature = false }
prost = { version = "0.11", default-features = false }
displaydoc = { version = "0.2", default-features = false }
bytes = { version = "1.2.1", default-features = false }
eyre = { version = "0.6", default-features = false }
serde_derive = { version = "1.0.104", default-features = false, optional = true }
serde = { version = "1.0", default-features = false, optional = true }
serde_json = { version = "1", default-features = false, optional = true }
erased-serde = { version = "0.3", default-features = false, features = ["alloc"], optional = true }
k256 = { version = "0.13", features = ["ecdsa", "sha256"], default-features = false }
tendermint = { version = "0.32", features = ["secp256k1", "rust-crypto"], default-features = false }
rand_core = { version = "0.6", default-feature = false }
subtle-encoding = { version = "0.5", features = ["bech32-preview"], default-features = false }
ecdsa = { version = "0.16", default-features = false }

## for codec encode or decode
parity-scale-codec = { version = "3.0.0", default-features = false, features = ["full"], optional = true }
scale-info = { version = "2.1.2", default-features = false, features = ["derive"], optional = true }
## for borsh encode or decode
borsh = {version = "0.10.0", default-features = false, optional = true }

[dev-dependencies]
hex-literal = "0.4"

[features]
default = ["std"]
std = [
    "ibc/std",
    "ibc-proto/std",
    "prost/std",
    "displaydoc/std",
    "bytes/std",
    "serde/std",
    "serde_json/std",
    "erased-serde/std",
    "k256/std",
    "tendermint/std",
    "rand_core/std",
    "subtle-encoding/std",
    "ecdsa/std",
]
# This feature is required for token transfer (ICS-20)
serde = ["dep:serde", "dep:serde_derive", "serde_json", "erased-serde"]
parity-scale-codec = ["dep:parity-scale-codec", "dep:scale-info"]
borsh = ["dep:borsh"]

[patch.crates-io]
ibc-proto = { git = "https://github.com/octopus-network/ibc-proto-rs.git", branch = "new-proto-v0.29.0" }
